# Generated by Django 5.2 on 2025-04-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente_dato', models.CharField(blank=True, max_length=100, null=True)),
                ('confiabilidad', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('usuario_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.variable')),
            ],
        ),
    ]
